const lorem =
    """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a porttitor est. Aliquam tristique tellus vel volutpat ullamcorper. Fusce in mi vitae augue condimentum blandit. Nulla non convallis dui. Etiam porttitor tortor mauris, eget rhoncus libero aliquet vel. Aliquam ut volutpat nibh, quis aliquam justo. Phasellus id ante lorem. Nam ipsum nibh, vulputate ac magna sed, accumsan mollis orci. Integer ornare dui lorem, mattis eleifend ligula pretium ac. Donec lobortis ultrices nulla. Maecenas lectus libero, consequat nec fringilla vel, facilisis quis tortor. Aenean laoreet maximus odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In consectetur sapien eu augue ultrices elementum.

Etiam congue sem pretium molestie commodo. Curabitur justo tortor, convallis non malesuada vel, tempor et leo. Vivamus egestas justo nunc, ut mollis arcu fringilla ac. Nunc sed euismod diam. Vivamus facilisis, justo sit amet posuere commodo, mi orci imperdiet urna, eget tincidunt neque est a sapien. Fusce vitae pretium nisl. Cras elementum sit amet nisi quis fringilla. Nam vitae erat dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Sed erat diam, condimentum eu dui eu, scelerisque aliquet magna. Nunc eget velit sed justo consequat scelerisque in vel dui. Quisque ullamcorper tortor eget efficitur vulputate. Nunc euismod auctor quam id convallis. In et leo tincidunt orci scelerisque pharetra ut non lectus. Vestibulum non dolor lobortis, molestie est vitae, auctor massa. Vestibulum viverra nunc eget ullamcorper volutpat. Vestibulum at enim leo. Quisque augue odio, sodales eget enim et, suscipit aliquam quam. Nam ut nisi sapien. Praesent accumsan commodo nisi, ut tristique augue tincidunt quis.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque et blandit ligula, et interdum neque. Aliquam condimentum, orci vel varius vehicula, nisi massa dictum mauris, sit amet dictum nulla nunc et arcu. Sed non viverra erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus cursus, risus sit amet suscipit finibus, nunc nulla aliquam eros, eu faucibus ante nulla vitae nibh. Vivamus eget erat lectus.

Nam vitae mauris sollicitudin, vestibulum tellus non, fermentum tellus. Donec viverra cursus consectetur. Vestibulum ac maximus nisi. Quisque ante ligula, dictum ut justo non, volutpat porta dui. Integer pretium blandit dui at interdum. Morbi imperdiet consectetur imperdiet. Maecenas auctor eleifend est ut dapibus. Proin felis ligula, volutpat quis dui nec, dapibus hendrerit purus. Integer vitae ante hendrerit, hendrerit felis vel, blandit justo. Integer in massa pellentesque, faucibus metus luctus, maximus eros. """;
